version: "3.3"
services:
  web:
    image: nginx:alpine
    ports:
      - 8086:80
    volumes:
      - C:\cursos\docker\SchoolOfNet\06-VolumeBind\data:/usr/share/nginx/html
  web2:
    image: nginx:alpine
    ports:
      - 8087:80
    volumes:
      - C:\cursos\docker\SchoolOfNet\06-VolumeBind\data:/usr/share/nginx/html
